spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: mongodb://localhost:27017/orders_db
      password: admin
      username: admin
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

services:
  external-product-integration:
    url: http://localhost:8081